services:
  kafka:
    image: faberchri/fast-data-dev
    ports:
      - 3030:3030
      - 9092:9092
    environment:
      - ADV_HOST=192.168.1.26
    links:
      - minio
  minio:
    image: quay.io/minio/minio
    command: [server, /data]
    environment:
      - MINIO_CONSOLE_ADDRESS=:9001
    ports:
      - 9001:9001
    volumes:
      - ./data:/data